# Generated by Django 3.1.7 on 2021-02-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iconcept4', '0002_auto_20210209_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ic4_callover_exception',
            name='Entery_Date',
        ),
        migrations.RemoveField(
            model_name='ic4_callover_exception',
            name='Exception_Details',
        ),
        migrations.RemoveField(
            model_name='ic4_callover_exception',
            name='IC4_Inputter',
        ),
        migrations.RemoveField(
            model_name='ic4_callover_exception',
            name='Other_Recievers',
        ),
        migrations.RemoveField(
            model_name='ic4_callover_exception',
            name='Owner_Details',
        ),
        migrations.RemoveField(
            model_name='ic4_callover_exception',
            name='Trans_ID',
        ),
        migrations.AddField(
            model_name='ic4_callover_exception',
            name='Exception_Detail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ic4_callover_exception',
            name='Other_Receivers',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ic4_callover_exception',
            name='Owner_Detail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
